### ISSUE TITLE
Allow eliding the attribute name for construction/with when there is only one

### ISSUE THREAD

**Issue by singpolyma** [tomdalling/value_semantics#2]
If there is only one attribute, it would be nice to allow syntax:

    Thing.new(1)

and

    athing.with(1)

**Comment by tomdalling** [comment]
Hi Stephen. Thanks for the suggestion.

Could you give me one or two usage scenarios? I'd like to get an idea of where it's most useful.

Personally, I would use a custom constructor for this. Something like:

```ruby
class Money
  include ValueSemantics.for_attributes { cents }

  def self.[](cents)
    new(cents: cents)
  end
end

m = Money[1_23]
```

**Comment by singpolyma** [comment]
> Personally, I would use a custom constructor for this. Something like:

I could use a custom constructor (either as you show, or override initialize and call super) -- however I have a largish number of such classes (representing the AST of a programming language these classes are the leaf nodes) and avoiding such boilerplate in ever class is one of the main draws of value_semantics for me.

**Comment by tomdalling** [comment]
To follow up on this one, I think the use case is rare enough that it should not get special consideration. It would involve changing the current behaviour of `.new`, which raises a (usually) helpful exception like "you tried to initialize this class with an Integer instead of a hash". **But**, you can implement this use case with a little bit of metaprogramming, using `ClassName.value_semantics.attributes`. It would look something like this:

```ruby
class BaseClass
  def self.single_attribute(&block)
    include ValueSemantics.for_attributes(&block)
    include SingleAttrOverrides
  end

  module SingleAttrOverrides
    def initialize(arg)
      attr = self.class.value_semantics.attributes.first
      super(attr.name => arg)
    end

    def with(arg)
      self.class.new(arg)
    end
  end
end

class Whatever < BaseClass
  single_attribute { foo String }
end

w = Whatever.new("HEELLLLOOO")
w2 = w.with("kbye")
puts w2.foo #=> "kbye"
```

The code for `dhall-ruby` looks cool, by the way. I recently used ValueSemantics for AST nodes too.
