### ISSUE TITLE
Allow `with` to work on protected attributes

### ISSUE THREAD

**Issue by singpolyma** [tomdalling/value_semantics#3]
I would like to have a ValueSemantics object where some/all of the attributes are protected.  This is easy:

```ruby
class X
  value_semantics do
    something String
  end

  protected :something
end
```

However, if I do this then `X.new(something: "hai").with(something: "wut")` does not work.  This is because `with` relies on `to_h` and `to_h` uses `public_send`.  Now, `to_h` probably *should* use `public_send` since otherwise it would allow getting a hash with values that were otherwise protected, probably not the intent.  However, there is not reason for `with` to be banned here because the constructor is not banned so creating a value with this attributes is fine.

**Comment by tomdalling** [comment]
Hi Stephen,

I had a think about how `protected`/`private` attrs should behave, and this is what I've landed on:

- `#with` should accept `protected`/`private` attrs because, as you mentioned, they can already be passed to `#initialize` to create new instances.

- `#[]` should still use `public_send`, since it's basically an attr reader method.

- `#to_h` should use `__send__` based on the recommendations in [zverok/good-value-object](https://github.com/zverok/good-value-object):
    
    >
    > Always try to provide `#to_h`, it is really good for serialization:
    >
    >   - `#to_h` should probably return hash with symbolic keys, containing exactly all the structural elements of value object and nothing more;
    >
    >   - If value object's constructor uses keyword arguments, `ValueType.new(**value.to_h) == value` should be always true
    >

Switching to `__send__` in `#to_h` should fix all the exceptions you were running into, and I've also added some tests around it. I'll make a new patch-level release shortly.

Thanks!
